#!/bin/bash

set -e

# find shmig, defaulting to local
if [ -e "$PWD/shmig" ]; then
    shmig="$PWD/shmig"
elif [ -e "$PWD/../shmig" ]; then
    shmig="$PWD/../shmig"
elif command -v shmig &>/dev/null; then
    shmig="$(command -v shmig)"
else
    >&2 echo "E: Can't find shmig command. Can't proceed."
    exit 1
fi

# Clean the environment, just to be sure
rm -Rf /tmp/shmig-test

# Create the test filesystem structure and enter it
mkdir -p /tmp/shmig-test/test{1,2,3,4}
cd /tmp/shmig-test

# Create normal config file
cat << EOF > shmig.conf
TYPE=sqlite3
DATABASE=test.sqlite3
MIGRATIONS=test1
EOF

# Run shmig and test that it created a migration according to the config file
if ! "$shmig" create test1 >/dev/null; then
    >&2 echo "E: shmig failed! Can't proceed with test."
    exit 2
fi
if ! find test1 -name '*test1.sql' &>/dev/null; then
    >&2 echo "E: shmig didn't create the expected migration. Test can't proceed."
    exit 3
fi


# Now create a local config file and test again
echo "MIGRATIONS=test2" > shmig.local.conf
if ! "$shmig" create test2 >/dev/null; then
    >&2 echo "E: shmig failed! Can't proceed with test."
    exit 4
fi
if ! find test2 -name '*test2.sql' &>/dev/null; then
    >&2 echo "FAIL: shmig didn't see the local config file."
    exit 100
else
    echo "PASS: shmig used local default config file shmig.local.conf"
fi


# Now let's try a custom config file

# Create custom config file
cat << EOF > shmig-custom.conf
TYPE=sqlite3
DATABASE=test.sqlite3
MIGRATIONS=test3
EOF

# Run shmig and test that it created a migration according to the config file
if ! "$shmig" -c shmig-custom.conf create test3 >/dev/null; then
    >&2 echo "E: shmig failed! Can't proceed with test."
    exit 5
fi
if ! find test3 -name '*test3.sql' &>/dev/null; then
    >&2 echo "E: shmig didn't create the expected migration. Test can't proceed."
    exit 6
fi


# Now create a local config file and test again
echo "MIGRATIONS=test4" > shmig-custom.local.conf
if ! "$shmig" -c shmig-custom.conf create test4 >/dev/null; then
    >&2 echo "E: shmig failed! Can't proceed with test."
    exit 7
fi
if ! find test4 -name '*test4.sql' &>/dev/null; then
    >&2 echo "FAIL: shmig didn't see the local custom config file."
    exit 101
else
    echo "PASS: shmig used local custom config file shmig-custom.local.conf"
fi



# Clean up
rm -Rf /tmp/shmig-test

